# Generated by Django 2.1.5 on 2019-02-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_affector',
            field=models.BooleanField(default=False),
        ),
    ]
