# Generated by Django 2.1.5 on 2019-02-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190206_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age_range',
            field=models.IntegerField(null=True, verbose_name='연령대'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=250, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=25, null=True, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=25, null=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=250, verbose_name='별명'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, verbose_name='ID'),
        ),
    ]
